---@meta

---@alias Glorp.Color number[] # RGBA array: {r, g, b, a}

---@class Glorp.containerSettings
---@field enabled? boolean
---@field id? string
---@field x? number
---@field y? number
---@field w? number
---@field h? number
---@field layout? "horizontal"|"vertical"
---@field spacing? number
---@field label? string
---@field border? boolean
---@field borderColor? Glorp.Color
---@field backgroundColor? Glorp.Color
---@field scrollable? boolean
---@field scrollDirection? "horizontal"|"vertical"
---@field scrollBar? Glorp.scrollBarSettings
---@field showScrollbar? boolean
---@field padding? number
---@field paddingTop? number
---@field paddingRight? number
---@field paddingBottom? number
---@field paddingLeft? number
---@field alignment? { horizontal: "left"|"center"|"right", vertical: "top"|"center"|"bottom"}
---@field bar?  { x: number, y: number, w: number ,h: number ,color: table }

---@class Glorp.Container
---@field addButton? fun(self: Glorp.Container, settings: Glorp.ButtonSettings): Glorp.Container
---@field addImage? fun(self: Glorp.Container, settings: Glorp.ImageSettings): Glorp.Container
---@field addButtonList? fun(self: Glorp.Container, settings: Glorp.ButtonListSettings): Glorp.Container
---@field addText? fun(self: Glorp.Container, settings: Glorp.TextSettings): Glorp.Container
---@field addContainer? fun(self: Glorp.Container, settings: Glorp.Container): Glorp.Container
---@field addDropDown? fun(self: Glorp.Container, settings: Glorp.DropDownSettings): Glorp.Container
---@field addForm? fun(self: Glorp.Container, settings: Glorp.FormSettings): Glorp.Container
---@field addSlider? fun(self: Glorp.Container, settings: Glorp.SliderSettings): Glorp.Container
---@field addCheckBox? fun(self: Glorp.Container, settings: Glorp.CheckBoxSettings): Glorp.Container
---@field addRadioButton? fun(self: Glorp.Container, settings: Glorp.RadioButtonSettings): Glorp.Container
---@field getChild fun(self: Glorp.Container, id: string)

---@class Glorp.scrollBarSettings
---@field bar? Glorp.barSettings

---@class Glorp.barSettings
---@field id? string
---@field image? love.Image
---@field w? number
---@field h? number
---@field color? Glorp.Color
---@field showScrollBar? boolean

---@class Glorp.ButtonSettings
---@field id? string
---@field w? number
---@field h? number
---@field label? string
---@field layout? "horizontal"|"vertical"
---@field alignment? { horizontal: "left"|"center"|"right", vertical: "top"|"center"|"bottom"}
---@field font? string
---@field fn? function

---@class Glorp.SliderSettings
---@field id? string
---@field w? number
---@field h? number
---@field fn? function
---@field orientation? "horizontal"|"vertical"
---@field knob_w? number
---@field knob_h? number
---@field startValue? number
---@field groove_h? number
---@field sliderRangeMin? number
---@field sliderRangeMax? number
---@field grooveColor? Glorp.Color
---@field knobColor? Glorp.Color
---@field knobBorderColor? Glorp.Color
---@field onRelease? fun(value: number)

---@class Glorp.ButtonListSettings
---@field id? string
---@field w? number
---@field h? number
---@field label? string
---@field layout? "horizontal"|"vertical"
---@field alignment? { horizontal: "left"|"center"|"right", vertical: "top"|"center"|"bottom"}
---@field font? string
---@field fn? function

---@class Glorp.TextSettings
---@field id? string
---@field w? number
---@field h? number
---@field color? Glorp.Color
---@field text? string
---@field align? "left"|"center"|"right"
---@field font? string

---@class Glorp.ImageSettings
---@field label? string
---@field image? love.Image
---@field w? number
---@field h? number
---@field id? string
---@field x? number
---@field y? number

---@class Glorp.FormSettings
---@field label? string
---@field image? love.Image
---@field x? number
---@field y? number
---@field w? number
---@field h? number
---@field id? string
---@field fields? {name: string, label: string}
---@field font? love.Font
---@field color? Glorp.Color
---@field limit? number
---@field backgroundColor? Glorp.Color
---@field borderColor? Glorp.Color
---@field activeBorderColor? Glorp.Color
---@field onSubmit? function

---@class Glorp.DropDownSettings
---@field w? number
---@field h? number
---@field bgColor? Glorp.Color
---@field hoverColor? Glorp.Color
---@field textColor? Glorp.Color
---@field text? string
---@field align? "left"|"center"|"right"
---@field font? string
---@field id? string
---@field x? number
---@field y? number
---@field selectedIndex? number
---@field hoverOptionColor? Glorp.Color
---@field onSelect? fun(index: number, value: any)
---@field options? any[]

---@class Glorp.CheckBoxSettings
---@field w? number
---@field h? number
---@field id? string
---@field boxWidth? number
---@field boxHeight? number
---@field x? number
---@field y? number
---@field checkInset? number
---@field checked? boolean
---@field onRelease? fun(state: boolean)

---@class Glorp.RadioButtonSettings
---@field w? number
---@field h? number
---@field id? string
---@field label? string
---@field font? love.Font
---@field radius? number
---@field spacing? number
---@field checkInset? number
---@field checked? boolean
---@field onRelease? fun(state: boolean)
